<?php

namespace Database\Seeders;

use App\Enums\PropertyStatus;
use App\Models\Amenity;
use App\Models\Arrondissement;
use App\Models\Category;
use App\Models\City;
use App\Models\Property;
use App\Models\PropertyImage;
use App\Models\User;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $owner = User::find(1);

        if (! $owner) {
            return;
        }

        $categories = Category::pluck('id', 'name');
        $cities = City::pluck('id', 'name');
        $brazzavilleArrondissements = Arrondissement::whereHas('city', fn ($q) => $q->where('name', 'Brazzaville'))->pluck('id', 'name');
        $pointeNoireArrondissements = Arrondissement::whereHas('city', fn ($q) => $q->where('name', 'Pointe-Noire'))->pluck('id', 'name');
        $amenities = Amenity::pluck('id', 'name');

        $properties = [
            // === Brazzaville — Appartements ===
            [
                'title' => 'Appartement lumineux Poto-Poto',
                'description' => 'Bel appartement F2 situé au cœur de Poto-Poto. Salon spacieux, chambre climatisée, cuisine équipée. Idéal pour jeune actif ou couple. Immeuble sécurisé avec gardien.',
                'address' => 'Avenue de la Liberté, Poto-Poto Centre',
                'city' => 'Brazzaville',
                'arrondissement' => 'Poto-Poto',
                'category' => 'Appartement',
                'price' => 750000,
                'surface' => 65,
                'rooms' => 3,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'floor' => 3,
                'furnished' => true,
                'latitude' => -4.2634,
                'longitude' => 15.2429,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Cuisine équipée', 'Internet', 'Sécurité 24/7'],
            ],
            [
                'title' => 'Appartement F3 Bacongo',
                'description' => 'Grand appartement F3 dans une résidence calme à Bacongo. 2 chambres, grand salon, cuisine américaine, terrasse. Proche des écoles et commerces.',
                'address' => 'Rue des Cocotiers, Bacongo',
                'city' => 'Brazzaville',
                'arrondissement' => 'Bacongo',
                'category' => 'Appartement',
                'price' => 950000,
                'surface' => 90,
                'rooms' => 4,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'floor' => 1,
                'furnished' => true,
                'latitude' => -4.2781,
                'longitude' => 15.2484,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Cuisine équipée', 'Balcon', 'Parking', 'Groupe électrogène'],
            ],
            [
                'title' => 'Studio meublé Moungali',
                'description' => 'Studio fonctionnel et moderne à Moungali. Parfait pour étudiant ou jeune travailleur. Cuisineette, salle d\'eau, accès Internet. Proche arrêts de bus.',
                'address' => 'Rue de la Paix, Moungali',
                'city' => 'Brazzaville',
                'arrondissement' => 'Moungali',
                'category' => 'Studio',
                'price' => 350000,
                'surface' => 28,
                'rooms' => 1,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'floor' => 0,
                'furnished' => true,
                'latitude' => -4.2582,
                'longitude' => 15.2539,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Internet', 'Meublé'],
            ],
            // === Brazzaville — Maisons ===
            [
                'title' => 'Maison familiale Makélékélé',
                'description' => 'Maison de 4 chambres avec grand jardin à Makélékélé. Deux salons, cuisine équipée, garage pour 2 voitures. Quartier résidentiel calme et sécurisé.',
                'address' => 'Quartier Plateau, Makélékélé',
                'city' => 'Brazzaville',
                'arrondissement' => 'Makélékélé',
                'category' => 'Maison',
                'price' => 2500000,
                'surface' => 200,
                'rooms' => 6,
                'bedrooms' => 4,
                'bathrooms' => 2,
                'floor' => 0,
                'furnished' => false,
                'latitude' => -4.2876,
                'longitude' => 15.2321,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Jardin', 'Parking', 'Garage', 'Groupe électrogène', 'Forage d\'eau'],
            ],
            [
                'title' => 'Maison avec piscine Talangaï',
                'description' => 'Superbe maison de standing avec piscine à Talangaï. 3 chambres climatisées, grand salon sur terrasse, vue sur le fleuve. Résidence fermée avec gardien.',
                'address' => 'Corniche, Talangaï',
                'city' => 'Brazzaville',
                'arrondissement' => 'Talangaï',
                'category' => 'Maison',
                'price' => 3500000,
                'surface' => 280,
                'rooms' => 5,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floor' => 0,
                'furnished' => true,
                'latitude' => -4.2418,
                'longitude' => 15.2372,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Piscine', 'Jardin', 'Terrasse', 'Parking', 'Sécurité 24/7', 'Caméras'],
            ],
            [
                'title' => 'Maison économique Mfilou',
                'description' => 'Maison abordable de 2 chambres à Mfilou. Idéale pour petite famille. Cuisine, salle d\'eau, petite cour. Proche du marché et des écoles.',
                'address' => 'Lotissement Tsiémé, Mfilou',
                'city' => 'Brazzaville',
                'arrondissement' => 'Mfilou',
                'category' => 'Maison',
                'price' => 800000,
                'surface' => 80,
                'rooms' => 3,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'floor' => 0,
                'furnished' => false,
                'latitude' => -4.2315,
                'longitude' => 15.2871,
                'status' => PropertyStatus::RENTED,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Groupe électrogène'],
            ],
            // === Brazzaville — Villas ===
            [
                'title' => 'Villa haut standing Ouenzé',
                'description' => 'Magnifique villa de standing avec piscine et grand jardin paysager à Ouenzé. 5 chambres dont une suite parentale, salon double, salle à manger, cuisine équipée haut de gamme.',
                'address' => 'Quartier Résidentiel, Ouenzé',
                'city' => 'Brazzaville',
                'arrondissement' => 'Ouenzé',
                'category' => 'Villa',
                'price' => 4500000,
                'surface' => 400,
                'rooms' => 8,
                'bedrooms' => 5,
                'bathrooms' => 3,
                'floor' => 1,
                'furnished' => true,
                'latitude' => -4.2473,
                'longitude' => 15.2598,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Piscine', 'Jardin', 'Garage', 'Terrasse', 'Sécurité 24/7', 'Caméras', 'Groupe électrogène', 'Forage d\'eau'],
            ],
            [
                'title' => 'Villa moderne Bacongo',
                'description' => 'Villa contemporaine de 4 chambres à Bacongo. Finitions haut de gamme, cuisine ouverte, grande terrasse, piscine à débordement. Vue imprenable.',
                'address' => 'Quartier Plateau, Rue des Manguiers, Bacongo',
                'city' => 'Brazzaville',
                'arrondissement' => 'Bacongo',
                'category' => 'Villa',
                'price' => 3800000,
                'surface' => 350,
                'rooms' => 6,
                'bedrooms' => 4,
                'bathrooms' => 2,
                'floor' => 0,
                'furnished' => true,
                'latitude' => -4.2785,
                'longitude' => 15.2456,
                'status' => PropertyStatus::SOLD,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Piscine', 'Jardin', 'Terrasse', 'Garage', 'Caméras'],
            ],
            // === Brazzaville — Bureaux & Commerces ===
            [
                'title' => 'Bureau centre-ville Poto-Poto',
                'description' => 'Bureau spacieux au cœur du quartier des affaires. Open space climatisé, cuisine partagée, salle de réunion. Accès Internet fibre optique.',
                'address' => 'Avenue Matsoua, Poto-Poto',
                'city' => 'Brazzaville',
                'arrondissement' => 'Poto-Poto',
                'category' => 'Bureau',
                'price' => 1200000,
                'surface' => 80,
                'rooms' => 4,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'floor' => 4,
                'furnished' => true,
                'latitude' => -4.2648,
                'longitude' => 15.2441,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Internet', 'Ascenseur', 'Groupe électrogène'],
            ],
            [
                'title' => 'Local commercial Bacongo',
                'description' => 'Local commercial de 100 m² en plein marché de Bacongo. Grande vitrine, réserve, climatisation. Idéal pour boutique, pharmacie ou agence.',
                'address' => 'Marché Bacongo, Avenue Mfoa',
                'city' => 'Brazzaville',
                'arrondissement' => 'Bacongo',
                'category' => 'Commerce',
                'price' => 1500000,
                'surface' => 100,
                'rooms' => 3,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'floor' => 0,
                'furnished' => false,
                'latitude' => -4.2792,
                'longitude' => 15.2491,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Sécurité 24/7'],
            ],
            // === Brazzaville — Duplex & Immeubles ===
            [
                'title' => 'Duplex moderne Moungali',
                'description' => 'Superbe duplex de 3 chambres avec toit-terrasse à Moungali. Vu dégagée sur la ville. Cuisine équipée, grand salon sur deux niveaux.',
                'address' => 'Quartier Résidentiel, Moungali',
                'city' => 'Brazzaville',
                'arrondissement' => 'Moungali',
                'category' => 'Duplex',
                'price' => 2000000,
                'surface' => 160,
                'rooms' => 5,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floor' => 2,
                'furnished' => true,
                'latitude' => -4.2571,
                'longitude' => 15.2524,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Terrasse', 'Parking', 'Internet', 'Groupe électrogène'],
            ],
            [
                'title' => 'Immeuble rapport Makélékélé',
                'description' => 'Immeuble de 6 appartements (3 F2, 2 F3, 1 studio) à Makélékélé. Revenu locatif mensuel garanti. Tous les lots sont loués. Excellent investissement.',
                'address' => 'Avenue principale, Makélékélé',
                'city' => 'Brazzaville',
                'arrondissement' => 'Makélékélé',
                'category' => 'Immeuble',
                'price' => 85000000,
                'surface' => 500,
                'rooms' => 12,
                'bedrooms' => 8,
                'bathrooms' => 6,
                'floor' => 3,
                'furnished' => false,
                'latitude' => -4.2881,
                'longitude' => 15.2335,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Ascenseur', 'Parking', 'Groupe électrogène', 'Sécurité 24/7'],
            ],
            // === Brazzaville — Appartements supplémentaires ===
            [
                'title' => 'Appartement meublé Ouenzé',
                'description' => 'Bel appartement F2 meublé dans une résidence moderne à Ouenzé. Cuisine équipée, climatisation, balcon. Parking privé et groupe électrogène.',
                'address' => 'Rue des Palmiers, Ouenzé',
                'city' => 'Brazzaville',
                'arrondissement' => 'Ouenzé',
                'category' => 'Appartement',
                'price' => 650000,
                'surface' => 55,
                'rooms' => 3,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'floor' => 2,
                'furnished' => true,
                'latitude' => -4.2465,
                'longitude' => 15.2605,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Cuisine équipée', 'Balcon', 'Parking', 'Groupe électrogène', 'Internet'],
            ],
            [
                'title' => 'Appartement économique Madibou',
                'description' => 'Appartement F1 fonctionnel à Madibou. Idéal pour célibataire. Pièce principale, kitchenette, salle d\'eau. Tranquille et abordable.',
                'address' => 'Cité Madibou, Rue 12',
                'city' => 'Brazzaville',
                'arrondissement' => 'Madibou',
                'category' => 'Appartement',
                'price' => 250000,
                'surface' => 35,
                'rooms' => 2,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'floor' => 0,
                'furnished' => false,
                'latitude' => -4.2381,
                'longitude' => 15.2795,
                'status' => PropertyStatus::RENTED,
                'is_verify' => false,
                'is_active' => true,
                'amenities' => [],
            ],
            // === Pointe-Noire — Appartements ===
            [
                'title' => 'Appartement vue mer Loandjili',
                'description' => 'Magnifique appartement F3 face à l\'océan à Loandjili. 2 chambres, grand séjour avec baie vitrée, cuisine équipée, climatisation centralisée.',
                'address' => 'Corniche Loandjili',
                'city' => 'Pointe-Noire',
                'arrondissement' => 'Loandjili',
                'category' => 'Appartement',
                'price' => 1200000,
                'surface' => 95,
                'rooms' => 4,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'floor' => 5,
                'furnished' => true,
                'latitude' => -4.7782,
                'longitude' => 11.8634,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Cuisine équipée', 'Parking', 'Ascenseur', 'Internet'],
            ],
            [
                'title' => 'Studio centre-ville Patrice Lumumba',
                'description' => 'Studio moderne en plein centre de Pointe-Noire. Cuisine équipée, climatisation, accès Internet. À deux pas des commerces et restaurants.',
                'address' => 'Avenue Charles de Gaulle, Centre',
                'city' => 'Pointe-Noire',
                'arrondissement' => 'Patrice Emery Lumumba',
                'category' => 'Studio',
                'price' => 400000,
                'surface' => 30,
                'rooms' => 1,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'floor' => 2,
                'furnished' => true,
                'latitude' => -4.7698,
                'longitude' => 11.8732,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Cuisine équipée', 'Internet', 'Meublé'],
            ],
            // === Pointe-Noire — Maisons ===
            [
                'title' => 'Maison de ville Mvou-Mvou',
                'description' => 'Jolie maison de ville de 3 chambres à Mvou-Mvou. Cour intérieure, cuisine équipée, garage. Quartier calme et familial.',
                'address' => 'Quartier Résidentiel, Mvou-Mvou',
                'city' => 'Pointe-Noire',
                'arrondissement' => 'Mvou-Mvou',
                'category' => 'Maison',
                'price' => 1500000,
                'surface' => 130,
                'rooms' => 4,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floor' => 0,
                'furnished' => false,
                'latitude' => -4.7815,
                'longitude' => 11.8819,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Parking', 'Garage', 'Groupe électrogène'],
            ],
            [
                'title' => 'Maison avec jardin Ngombe',
                'description' => 'Belle maison de 4 chambres avec grand jardin tropical à Ngombe. Véranda, cuisine équipée, dépendance pour un gardien. Puits et groupe électrogène.',
                'address' => 'Quartier Ngombe, Zone Ouest',
                'city' => 'Pointe-Noire',
                'arrondissement' => 'Ngombe',
                'category' => 'Maison',
                'price' => 2200000,
                'surface' => 180,
                'rooms' => 5,
                'bedrooms' => 4,
                'bathrooms' => 2,
                'floor' => 0,
                'furnished' => false,
                'latitude' => -4.7911,
                'longitude' => 11.8694,
                'status' => PropertyStatus::RENTED,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Jardin', 'Parking', 'Groupe électrogène', 'Forage d\'eau'],
            ],
            // === Pointe-Noire — Villas ===
            [
                'title' => 'Villa de luxe Loandjili',
                'description' => 'Villa d\'exception avec accès direct à la plage à Loandjili. 5 chambres suites, piscine à débordement, jardin tropical, terrasse panoramique. Domaine sécurisé.',
                'address' => 'Bord de mer, Loandjili',
                'city' => 'Pointe-Noire',
                'arrondissement' => 'Loandjili',
                'category' => 'Villa',
                'price' => 5500000,
                'surface' => 450,
                'rooms' => 8,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'floor' => 1,
                'furnished' => true,
                'latitude' => -4.7765,
                'longitude' => 11.8612,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Piscine', 'Jardin', 'Terrasse', 'Parking', 'Sécurité 24/7', 'Caméras', 'Groupe électrogène', 'Forage d\'eau'],
            ],
            [
                'title' => 'Villa moderne Indiana',
                'description' => 'Villa récente de 4 chambres dans le lotissement Indiana à Pointe-Noire. Finitions modernes, cuisine équipée, climatisation réversible, jardin paysager.',
                'address' => 'Lotissement Indiana, Zone Ouest',
                'city' => 'Pointe-Noire',
                'arrondissement' => 'Indiana',
                'category' => 'Villa',
                'price' => 3200000,
                'surface' => 300,
                'rooms' => 6,
                'bedrooms' => 4,
                'bathrooms' => 2,
                'floor' => 0,
                'furnished' => true,
                'latitude' => -4.7853,
                'longitude' => 11.8557,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Jardin', 'Garage', 'Terrasse', 'Caméras', 'Groupe électrogène'],
            ],
            // === Pointe-Noire — Bureaux & Commerces ===
            [
                'title' => 'Bureau moderne Patrice Lumumba',
                'description' => 'Bureau d\'affaires entièrement équipé au centre-ville de Pointe-Noire. Salle de réunion, espace open space, cuisine, fibre optique. Vue sur l\'avenue.',
                'address' => 'Avenue Charles de Gaulle, Immeuble Fidèle',
                'city' => 'Pointe-Noire',
                'arrondissement' => 'Patrice Emery Lumumba',
                'category' => 'Bureau',
                'price' => 1000000,
                'surface' => 70,
                'rooms' => 4,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'floor' => 3,
                'furnished' => true,
                'latitude' => -4.7702,
                'longitude' => 11.8739,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Internet', 'Ascenseur', 'Groupe électrogène'],
            ],
            [
                'title' => 'Local commercial Tié-Tié',
                'description' => 'Local commercial de 80 m² dans le quartier très animé de Tié-Tié. Grande devanture, mezzanine, climatisation. Idéal pour restaurant ou supérette.',
                'address' => 'Marché Tié-Tié, Rue principale',
                'city' => 'Pointe-Noire',
                'arrondissement' => 'Tié-Tié',
                'category' => 'Commerce',
                'price' => 1800000,
                'surface' => 80,
                'rooms' => 3,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'floor' => 0,
                'furnished' => false,
                'latitude' => -4.7832,
                'longitude' => 11.8867,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Sécurité 24/7'],
            ],
            // === Pointe-Noire — Duplex & Immeuble ===
            [
                'title' => 'Duplex vue océan Loandjili',
                'description' => 'Superbe duplex avec vue panoramique sur l\'océan. 3 chambres, grand salon double hauteur, terrasse de 50 m², cuisine haut de gamme. Prestations luxueuses.',
                'address' => 'Corniche Loandjili, Résidence Océan',
                'city' => 'Pointe-Noire',
                'arrondissement' => 'Loandjili',
                'category' => 'Duplex',
                'price' => 2800000,
                'surface' => 180,
                'rooms' => 5,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floor' => 2,
                'furnished' => true,
                'latitude' => -4.7778,
                'longitude' => 11.8629,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Terrasse', 'Parking', 'Internet', 'Groupe électrogène', 'Cuisine équipée'],
            ],
            [
                'title' => 'Immeuble de rapport Tié-Tié',
                'description' => 'Immeuble de 8 appartements à Tié-Tié (4 F2, 3 F3, 1 commerce en RDC). Revenus locatifs mensuels intéressants. Investissement rentable.',
                'address' => 'Avenue de l\'Indépendance, Tié-Tié',
                'city' => 'Pointe-Noire',
                'arrondissement' => 'Tié-Tié',
                'category' => 'Immeuble',
                'price' => 95000000,
                'surface' => 600,
                'rooms' => 15,
                'bedrooms' => 10,
                'bathrooms' => 8,
                'floor' => 4,
                'furnished' => false,
                'latitude' => -4.7839,
                'longitude' => 11.8875,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Ascenseur', 'Parking', 'Groupe électrogène', 'Sécurité 24/7'],
            ],
            // === Pointe-Noire — Appartement supplémentaire ===
            [
                'title' => 'Appartement F2 résidentiel Mvou-Mvou',
                'description' => 'Appartement F2 calme et lumineux dans une résidence à Mvou-Mvou. Salon, chambre climatisée, cuisine équipée, balcon. Résidence avec gardien et parking.',
                'address' => 'Cité Résidentielle, Mvou-Mvou',
                'city' => 'Pointe-Noire',
                'arrondissement' => 'Mvou-Mvou',
                'category' => 'Appartement',
                'price' => 550000,
                'surface' => 60,
                'rooms' => 3,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'floor' => 1,
                'furnished' => true,
                'latitude' => -4.7808,
                'longitude' => 11.8825,
                'status' => PropertyStatus::AVAILABLE,
                'is_verify' => true,
                'is_active' => true,
                'amenities' => ['Climatisation', 'Cuisine équipée', 'Balcon', 'Parking', 'Groupe électrogène', 'Internet'],
            ],
        ];

        foreach ($properties as $index => $data) {
            $cityName = $data['city'];
            $arrondissementName = $data['arrondissement'];
            $categoryName = $data['category'];
            $amenityNames = $data['amenities'];
            unset($data['city'], $data['arrondissement'], $data['category'], $data['amenities']);

            $cityId = $cities[$cityName] ?? null;
            $categoryId = $categories[$categoryName] ?? null;

            if ($cityName === 'Brazzaville') {
                $arrondissementId = $brazzavilleArrondissements[$arrondissementName] ?? null;
            } else {
                $arrondissementId = $pointeNoireArrondissements[$arrondissementName] ?? null;
            }

            $data['city_id'] = $cityId;
            $data['category_id'] = $categoryId;
            $data['arrondissement_id'] = $arrondissementId;
            $data['created_by'] = $owner->id;

            $property = Property::create($data);

            // Lier les amenities
            foreach ($amenityNames as $amenityName) {
                if (isset($amenities[$amenityName])) {
                    $property->amenities()->attach($amenities[$amenityName]);
                }
            }

            // Créer les images de démonstration
            $this->createDemoImages($property, $index);
        }
    }

    private function createDemoImages(Property $property, int $index): void
    {
        $images = [
            [
                'url' => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
                'cover_image' => true,
            ],
            [
                'url' => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
                'cover_image' => false,
            ],
            [
                'url' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
                'cover_image' => false,
            ],
        ];

        foreach ($images as $image) {
            PropertyImage::create([
                'property_id' => $property->id,
                'image_url' => $image['url'],
                'cover_image' => $image['cover_image'],
            ]);
        }
    }
}
